name = "MadNLPGPU"
uuid = "d72a61cc-809d-412f-99be-fd81f4b8a598"
authors = ["Sungho Shin <sungho.shin.ss@gmail.com>"]
version = "0.3.0"

[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
CUDAKernels = "72cfdca4-0801-4ab0-bf6a-d52aa10adc57"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
CUDA = "~2,~3"
CUDAKernels = "0.3.0"
KernelAbstractions = "0.7"
julia = "1.5"


[targets]
test = ["Test", "MadNLPTests"]
